[[procedures]]
fname = "test_function.py"
function_name = "main"
procedure_name = ["STORAGE_DATABASE", "CPW_DATA", "test2"]
packages=[
            "snowflake-snowpark-python",
            "pandas"
        ]

[[procedures]]
fname = "sproc_elt.py"
function_name = "combine_trout_tables"
procedure_name = ["STORAGE_DATABASE", "CPW_DATA", "sproc_elt"]
packages=[
            "snowflake-snowpark-python",
            "pandas"
        ]

[stage]
fully_qualified_name = "STORAGE_DATABASE.CPW_DATA.TEST_STAGE"
stage_database = "STORAGE_DATABASE"
stage_schema = "CPW_DATA"
stage_name = "TEST_STAGE"