name: CI/CD

on:
  pull_request:
  push:
    
jobs:

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"

