name: CI/CD

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    
jobs:

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"

  test:
      runs-on: windows-latest

      strategy:
          matrix:
              python-version: [3.10.11]
      steps:
          - uses: actions/checkout@v3
          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
  
          - name: Install dependencies
            run: 
              python -m pip install --upgrade pip
              pip install -r requirements.txt
  
          - name: Run tests
            run: pytest

  deploy:
      runs-on: windows-latest
      if:  github.ref == 'refs/heads/main'
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
  
      - name: Deploy Functions
        run: python snowflake_deployment.py
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER: ${{ secrets.USER }}