name: CI/CD

on: push
    
jobs:

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"

  test:
    runs-on: windows-latest

    strategy:
        matrix:
            python-version: [3.10.11]
    steps:
        - uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: pytest

  deploy_procedures:
      needs: [lint, test]
      runs-on: windows-latest
      if:  github.ref == 'refs/heads/main'

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Functions
        run: python snowflake_deployment.py
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER: ${{ secrets.USER }}


  deploy_sql_files:
    needs: [deploy_procedures]
    runs-on: windows-latest
    if:  github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute SQL files
      run: python snowflake_execute_sql_files.py
      env:
        ACCOUNT: ${{ secrets.ACCOUNT }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USER: ${{ secrets.USER }}

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Commit changes made by Python script"
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}