name: Unit Tests

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: windows-latest

        strategy:
            matrix:
                python-version: [3.10]
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
    
            - name: Install dependencies
              run: 
                python -m pip install --upgrade pip
                pip install requirements.txt
    
            - name: Run tests
              run: python pytest
